name: Traffic stats

on:
  schedule:
    - cron: "0 0 * * 1" # end of Sunday, 00:00 UTC Monday
  workflow_dispatch:

permissions: {}

jobs:
  stats:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: scripts
      - name: Update gist
        run: python scripts/traffic.py
        env:
          TRAFFIC_TOKEN: ${{ secrets.TRAFFIC_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          REPO: ${{ github.repository }}